version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "security"
    versioning-strategy: "lockfile-only"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "mypy*"
          - "coverage*"
      production-dependencies:
        patterns:
          - "sqlalchemy*"
          - "python-telegram-bot*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      actions:
        patterns:
          - "*" 